version: '3.1'
services:
  postgres:
    container_name: postgres
    image: postgres
    ports : 
    - 5433:5432
    environment:
      POSTGRES_USER : root
      POSTGRES_PASSWORD : root
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      
  test:
    container_name: postgres_test
    image: postgres
    ports : 
    - 5434:5432
    environment:
      POSTGRES_USER : root
      POSTGRES_PASSWORD : root
  
  
    